# Generated by Django 5.0.10 on 2026-02-17 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('item_type', models.CharField(choices=[('likert5', 'Likert 1–5'), ('yesno', 'Yes/No'), ('text', 'Free text')], default='likert5', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('show_feedback_immediately', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['study_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='delphi.panelist')),
            ],
        ),
        migrations.CreateModel(
            name='RoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_items', to='delphi.item')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_items', to='delphi.round')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('round', 'item')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('n', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('round_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='delphi.rounditem')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='delphi.study'),
        ),
        migrations.AddField(
            model_name='panelist',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='delphi.study'),
        ),
        migrations.AddField(
            model_name='item',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delphi.study'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='delphi.panelist')),
                ('round_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='delphi.rounditem')),
            ],
            options={
                'unique_together': {('panelist', 'round_item')},
            },
        ),
        migrations.CreateModel(
            name='RoundSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_submissions', to='delphi.panelist')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='delphi.round')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('panelist', 'round')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('study', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('study', 'email')},
        ),
    ]
