# Generated by Django 5.0.10 on 2026-02-16 18:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_code', models.CharField(max_length=50)),
                ('domain_tag', models.CharField(blank=True, max_length=100)),
                ('stem_text', models.TextField()),
                ('response_type', models.CharField(choices=[('LIKERT_5', 'Likert 5-point'), ('EITHER_OR', 'Either/Or')], default='LIKERT_5', max_length=16)),
                ('option_a', models.CharField(blank=True, max_length=255)),
                ('option_b', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order_index', 'stable_code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('show_feedback_immediately', models.BooleanField(default=False)),
                ('show_prior_round_rating', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='delphi.panelist')),
            ],
        ),
        migrations.CreateModel(
            name='RoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_items', to='delphi.item')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_items', to='delphi.round')),
            ],
            options={
                'ordering': ['item__order_index', 'item__stable_code'],
                'unique_together': {('round', 'item')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField(default=0)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('pct_agree', models.FloatField(blank=True, null=True)),
                ('pct_disagree', models.FloatField(blank=True, null=True)),
                ('consensus', models.BooleanField(default=False)),
                ('distribution_json', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('round_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='delphi.rounditem')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='delphi.study'),
        ),
        migrations.AddField(
            model_name='panelist',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='delphi.study'),
        ),
        migrations.AddField(
            model_name='item',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delphi.study'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likert_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('either_or_value', models.CharField(blank=True, max_length=1, null=True)),
                ('comment', models.TextField(blank=True)),
                ('suggested_revision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='delphi.panelist')),
                ('round_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='delphi.rounditem')),
            ],
            options={
                'unique_together': {('round_item', 'panelist')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='panelist',
            unique_together={('study', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('study', 'stable_code', 'version')},
        ),
    ]
