# Generated by Django 5.0.10 on 2026-02-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='matrix_columns',
            field=models.TextField(blank=True, help_text='JSON list of column headers for matrix questions'),
        ),
        migrations.AddField(
            model_name='item',
            name='matrix_rows',
            field=models.TextField(blank=True, help_text='JSON list of row labels for matrix questions'),
        ),
        migrations.AddField(
            model_name='item',
            name='option_f',
            field=models.CharField(blank=True, help_text='Option F (for multiple choice)', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('likert5', 'Likert 1–5 (Strongly Disagree to Strongly Agree)'), ('yesno', 'Yes/No'), ('multiple', 'Multiple Choice (Custom Options)'), ('text', 'Free text'), ('matrix', 'Matrix (Checkbox grid)'), ('checkbox', 'Checkbox (Select multiple)')], default='likert5', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_a',
            field=models.CharField(blank=True, help_text='Option A (for multiple choice)', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_b',
            field=models.CharField(blank=True, help_text='Option B (for multiple choice)', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_c',
            field=models.CharField(blank=True, help_text='Option C (for multiple choice)', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_d',
            field=models.CharField(blank=True, help_text='Option D (for multiple choice)', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_e',
            field=models.CharField(blank=True, help_text='Option E (for multiple choice)', max_length=500),
        ),
    ]
