# Generated by Django 5.0.10 on 2026-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='option_a',
            field=models.CharField(blank=True, help_text='Option A (for multiple choice)', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='option_b',
            field=models.CharField(blank=True, help_text='Option B (for multiple choice)', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='option_c',
            field=models.CharField(blank=True, help_text='Option C (for multiple choice)', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='option_d',
            field=models.CharField(blank=True, help_text='Option D (for multiple choice)', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='option_e',
            field=models.CharField(blank=True, help_text='Option E (for multiple choice)', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('likert5', 'Likert 1–5 (Strongly Disagree to Strongly Agree)'), ('yesno', 'Yes/No'), ('multiple', 'Multiple Choice (Custom Options)'), ('text', 'Free text')], default='likert5', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='prompt',
            field=models.TextField(help_text='The question or statement to present to panelists'),
        ),
    ]
