# Generated by Django 5.0.10 on 2026-02-21 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphi', '0002_item_option_a_item_option_b_item_option_c_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='consensus_reached',
            field=models.BooleanField(default=False, help_text='True if >=75% agreement'),
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='pct_agree',
            field=models.FloatField(blank=True, help_text='Percentage of 4 or 5 ratings', null=True),
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='pct_disagree',
            field=models.FloatField(blank=True, help_text='Percentage of 1 or 2 ratings', null=True),
        ),
        migrations.AddField(
            model_name='feedbackaggregate',
            name='std_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution/Affiliation', max_length=255),
        ),
        migrations.AddField(
            model_name='panelist',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
