# Generated by Django 5.0.10 on 2026-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphi', '0002_item_matrix_columns_item_matrix_rows_item_option_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='option_a',
            field=models.CharField(blank=True, help_text='Option A (for multiple choice)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_b',
            field=models.CharField(blank=True, help_text='Option B (for multiple choice)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_c',
            field=models.CharField(blank=True, help_text='Option C (for multiple choice)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_d',
            field=models.CharField(blank=True, help_text='Option D (for multiple choice)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_e',
            field=models.CharField(blank=True, help_text='Option E (for multiple choice)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='option_f',
            field=models.CharField(blank=True, help_text='Option F (for multiple choice)', max_length=5000),
        ),
    ]
