# Generated by Django 5.0.10 on 2026-03-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphi', '0003_alter_item_option_a_alter_item_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelist',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment from panelist', null=True),
        ),
    ]
